// packages/integrations/react/server/utils.ts
// Server-side utilities for React integration

import type { ComponentType } from 'react';
import type { ComponentMetadata } from '../types.ts';
import { join } from 'node:path';
import { toImportSpecifier } from '../../core/utils.ts';
import { resolveIslandPath } from '../../../avalon/src/islands/framework-detection.ts';

/**
 * Load a React component from file path
 *
 * @param src - Component source path
 * @returns React component
 */
export async function loadComponent(src: string): Promise<ComponentType<Record<string, unknown>>> {
	try {
		const resolvedSrc = await resolveIslandPath(src);

		// Resolve the component path
		// If path starts with /, it's relative to workspace root (e.g., /src/islands/Counter.tsx)
		// Otherwise, it's already an absolute path or relative to current file
		let componentPath: string;
		if (resolvedSrc.startsWith('/')) {
			// Remove leading slash and join with cwd
			componentPath = join(process.cwd(), resolvedSrc.slice(1));
		} else {
			componentPath = resolvedSrc;
		}

		// Import the component module
		const module = await import(/* @vite-ignore */ toImportSpecifier(componentPath));

		// Get the default export or named export
		const Component = module.default || module[Object.keys(module)[0]];

		if (!Component || typeof Component !== 'function') {
			throw new Error(`Invalid React component in ${src}: expected function, got ${typeof Component}`);
		}

		return Component as ComponentType<Record<string, unknown>>;
	} catch (error) {
		const errorMessage = error instanceof Error ? error.message : String(error);
		throw new Error(`Failed to load React component from ${src}: ${errorMessage}`, { cause: error });
	}
}

/**
 * Check if a component has "use client" directive
 *
 * @param src - Component source path
 * @returns True if component has "use client" directive
 */
export async function hasUseClientDirective(src: string): Promise<boolean> {
	try {
		const resolvedSrc = await resolveIslandPath(src);

		let componentPath: string;
		if (resolvedSrc.startsWith('/')) {
			componentPath = join(process.cwd(), resolvedSrc.slice(1));
		} else {
			componentPath = resolvedSrc;
		}

		const content = await readFile(componentPath, 'utf-8');

		// Check for "use client" directive at the top of the file
		// It should be one of the first statements (after imports/comments)
		const useClientPattern = /^['"]use client['"];?\s*$/m;
		return useClientPattern.test(content);
	} catch (error) {
		console.warn(`Failed to check "use client" directive in ${src}:`, error);
		return false;
	}
}

/**
 * Extract import statements from component file
 *
 * @param content - File content
 * @returns Array of import sources
 */
function extractImports(content: string): string[] {
	const imports: string[] = [];

	// Match ES6 imports: import ... from "source"
	const importPattern = /import\s+(?:[\w\s{},*]+\s+from\s+)?['"]([^'"]+)['"]/g;
	let match;

	while ((match = importPattern.exec(content)) !== null) {
		imports.push(match[1]);
	}

	return imports;
}

/**
 * Analyze component file for RSC classification
 *
 * @param filePath - Component file path
 * @returns Component metadata
 */
export async function analyzeComponent(filePath: string): Promise<ComponentMetadata> {
	try {
		const resolvedPath = await resolveIslandPath(filePath);

		let componentPath: string;
		if (resolvedPath.startsWith('/')) {
			componentPath = join(process.cwd(), resolvedPath.slice(1));
		} else {
			componentPath = resolvedPath;
		}

		const content = await readFile(componentPath, 'utf-8');

		// Check for directives
		const isClientComponent = /^['"]use client['"];?\s*$/m.test(content);
		const isServerComponent = /^['"]use server['"];?\s*$/m.test(content);

		// Check for async function components
		// Look for: export default async function, export async function, const Component = async
		const hasAsyncRender =
			/export\s+default\s+async\s+function/.test(content) ||
			/export\s+async\s+function/.test(content) ||
			/const\s+\w+\s*=\s*async\s+(?:function|\()/.test(content);

		// Extract dependencies
		const dependencies = extractImports(content);

		return {
			path: filePath,
			isClientComponent,
			isServerComponent,
			hasAsyncRender,
			dependencies,
		};
	} catch (error) {
		console.warn(`Failed to analyze component ${filePath}:`, error);
		return {
			path: filePath,
			isClientComponent: false,
			isServerComponent: false,
			hasAsyncRender: false,
			dependencies: [],
		};
	}
}

/**
 * Normalize and serialize component props
 * Removes non-serializable values like functions, symbols, etc.
 *
 * @param props - Raw props object
 * @returns Serialized props
 */
export function serializeProps(props: Record<string, unknown>): Record<string, unknown> {
	try {
		// JSON round-trip intentionally strips non-serializable values (functions, symbols)
		// structuredClone cannot handle these, so JSON.parse/stringify is used deliberately
		const json = JSON.stringify(props);
		return JSON.parse(json) as Record<string, unknown>;
	} catch (error) {
		console.warn('Failed to serialize props, returning empty object:', error);
		return {};
	}
}

// packages/integrations/lit/server/utils.ts
/**
 * Lit Server Utilities
 */

// Import DOM shim FIRST before any Lit imports
import './dom-shim.ts';

import type { LitElement, CSSResult } from 'lit';
import { join } from 'node:path';
import { readFile } from 'node:fs/promises';
import { toImportSpecifier } from '../../core/utils.ts';
import { resolveIslandPath } from '../../../avalon/src/islands/framework-detection.ts';

/**
 * Extract custom element tag name from a Lit component
 */
export function getTagName(ElementClass: typeof LitElement): string {
	const tagName = (ElementClass as any).elementName || (ElementClass as any).tagName || (ElementClass as any)._tagName;

	if (tagName && typeof tagName === 'string') {
		return tagName;
	}

	// Convert PascalCase to kebab-case
	const className = ElementClass.name;
	if (className) {
		return className.replaceAll(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
	}

	throw new Error('Could not determine tag name for Lit component');
}

function escapeAttributeValue(value: string): string {
	return value
		.replaceAll('&', '&amp;')
		.replaceAll('"', '&quot;')
		.replaceAll("'", '&#39;')
		.replaceAll('<', '&lt;')
		.replaceAll('>', '&gt;');
}

/**
 * Serialize props to HTML attributes
 */
export function serializeAttributes(props: Record<string, unknown>): string {
	const attributes: string[] = [];

	for (const [key, value] of Object.entries(props)) {
		if (value === undefined || value === null) continue;

		const attrName = key.replaceAll(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

		if (typeof value === 'boolean') {
			if (value) attributes.push(attrName);
		} else if (typeof value === 'string') {
			attributes.push(`${attrName}="${escapeAttributeValue(value)}"`);
		} else if (typeof value === 'number') {
			attributes.push(`${attrName}="${value}"`);
		} else if (typeof value === 'object') {
			try {
				attributes.push(`${attrName}='${escapeAttributeValue(JSON.stringify(value))}'`);
			} catch {
				/* skip */
			}
		}
	}

	return attributes.join(' ');
}

/**
 * Collect styles from Lit component
 */
export function collectStyles(ElementClass: typeof LitElement): string {
	try {
		const styles = (ElementClass as any).styles;
		if (!styles) return '';

		if (Array.isArray(styles)) {
			return styles.map(extractCssFromStyle).filter(Boolean).join('\n');
		}
		return extractCssFromStyle(styles);
	} catch {
		return '';
	}
}

function extractCssFromStyle(style: unknown): string {
	if (!style) return '';
	if (typeof style === 'string') return style;
	if (typeof style === 'object' && 'cssText' in style) {
		return (style as CSSResult).cssText;
	}
	if (typeof style === 'object' && 'toString' in style) {
		return (style as { toString(): string }).toString();
	}
	return '';
}

/**
 * Extract tag name from source code (avoids decorator issues)
 */
export async function extractTagNameFromSource(src: string): Promise<string | null> {
	try {
		const resolvedSrc = await resolveIslandPath(src);
		const componentPath = resolvedSrc.startsWith('/') ? join(process.cwd(), resolvedSrc.slice(1)) : resolvedSrc;

		const content = await readFile(componentPath, 'utf-8');

		// Try @customElement decorator with different quote styles
		const decoratorPatterns = [
			/@customElement\s*\(\s*"([^"]+)"\s*\)/,
			/@customElement\s*\(\s*'([^']+)'\s*\)/,
			/@customElement\s*\(\s*`([^`]+)`\s*\)/,
		];

		for (const pattern of decoratorPatterns) {
			const match = new RegExp(pattern).exec(content);
			if (match?.[1]) return match[1];
		}

		// Try static elementName property (for decorator-free components)
		const elementNamePatterns = [
			/static\s+elementName\s*=\s*"([^"]+)"/,
			/static\s+elementName\s*=\s*'([^']+)'/,
			/static\s+elementName\s*=\s*`([^`]+)`/,
		];

		for (const pattern of elementNamePatterns) {
			const match = new RegExp(pattern).exec(content);
			if (match?.[1]) return match[1];
		}

		return null;
	} catch {
		return null;
	}
}

/**
 * Load a Lit component from file path
 */
export async function loadComponent(
	src: string,
	viteServer?: { ssrLoadModule: (path: string) => Promise<Record<string, unknown>> },
): Promise<typeof LitElement> {
	const resolvedSrc = await resolveIslandPath(src);
	let module: Record<string, unknown>;

	if (viteServer) {
		module = await viteServer.ssrLoadModule(resolvedSrc);
	} else {
		const componentPath = resolvedSrc.startsWith('/') ? join(process.cwd(), resolvedSrc.slice(1)) : resolvedSrc;
		module = await import(/* @vite-ignore */ toImportSpecifier(componentPath));
	}

	const Component = module.default || module[Object.keys(module)[0]];

	if (!Component || typeof Component !== 'function') {
		throw new Error(`Invalid Lit component in ${src}`);
	}

	return Component as typeof LitElement;
}
