// www/app/modules/demo/components/Counter.qwik.tsx
/** @jsxImportSource @builder.io/qwik */
import { component$, useSignal } from '@builder.io/qwik';

export default component$(() => {
	const count = useSignal(0);

	return (
		<div style={{
			padding: '2rem',
			borderRadius: '12px',
			background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
			border: '1px solid rgba(172, 127, 244, 0.2)',
			textAlign: 'center',
			fontFamily: 'system-ui, sans-serif',
			color: '#e0e0e0',
			maxWidth: '320px',
		}}>
			<h3 style={{ margin: '0 0 0.5rem', color: '#ac7ff4', fontSize: '1.1rem' }}>
				Qwik Counter
			</h3>
			<p style={{ margin: '0 0 1rem', fontSize: '0.85rem', opacity: 0.7 }}>
				Resumable — no hydration needed
			</p>
			<div style={{ fontSize: '2.5rem', fontWeight: 700, margin: '1rem 0' }}>
				{count.value}
			</div>
			<div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'center' }}>
				<button
					onClick$={() => count.value--}
					style={{
						padding: '0.5rem 1.25rem',
						borderRadius: '8px',
						border: '1px solid rgba(172, 127, 244, 0.3)',
						background: 'rgba(172, 127, 244, 0.1)',
						color: '#ac7ff4',
						fontSize: '1.1rem',
						cursor: 'pointer',
					}}
				>
					−
				</button>
				<button
					onClick$={() => count.value++}
					style={{
						padding: '0.5rem 1.25rem',
						borderRadius: '8px',
						border: '1px solid rgba(172, 127, 244, 0.3)',
						background: 'rgba(172, 127, 244, 0.1)',
						color: '#ac7ff4',
						fontSize: '1.1rem',
						cursor: 'pointer',
					}}
				>
					+
				</button>
			</div>
		</div>
	);
});

// Avalon/src/islands/Counter.tsx
import { useState } from 'preact/hooks';

export default function Counter() {
	const [count, setCount] = useState(0);

	return (
		<div style={{
			padding: '24px',
			background: 'rgba(255,255,255,0.02)',
			border: '1px solid rgba(255,255,255,0.06)',
			borderRadius: '14px',
			textAlign: 'center',
			backdropFilter: 'blur(12px)',
		}}>
			<div style={{
				fontSize: '13px',
				fontWeight: '500',
				color: 'rgba(255,255,255,0.5)',
				marginBottom: '16px',
				letterSpacing: '0.02em',
			}}>
				Default Counter
			</div>
			
			<div style={{
				fontSize: '42px',
				fontWeight: '300',
				color: 'rgba(255,255,255,0.9)',
				marginBottom: '20px',
				fontFamily: "'DM Sans', sans-serif",
			}}>
				{count}
			</div>
			
			<div style={{ display: 'flex', gap: '8px', justifyContent: 'center' }}>
				<button
					onClick={() => setCount(c => c - 1)}
					style={{
						padding: '10px 20px',
						fontSize: '18px',
						background: 'rgba(255,255,255,0.06)',
						color: 'rgba(255,255,255,0.8)',
						border: '1px solid rgba(255,255,255,0.08)',
						borderRadius: '8px',
						cursor: 'pointer',
					}}
				>
					−
				</button>
				<button
					onClick={() => setCount(0)}
					style={{
						padding: '10px 16px',
						fontSize: '12px',
						background: 'rgba(255,255,255,0.04)',
						color: 'rgba(255,255,255,0.5)',
						border: '1px solid rgba(255,255,255,0.06)',
						borderRadius: '8px',
						cursor: 'pointer',
					}}
				>
					Reset
				</button>
				<button
					onClick={() => setCount(c => c + 1)}
					style={{
						padding: '10px 20px',
						fontSize: '18px',
						background: 'rgba(255,255,255,0.06)',
						color: 'rgba(255,255,255,0.8)',
						border: '1px solid rgba(255,255,255,0.08)',
						borderRadius: '8px',
						cursor: 'pointer',
					}}
				>
					+
				</button>
			</div>
		</div>
	);
}
