// packages/integrations/react/client/hydration.ts
// Client-side hydration logic for React components
/// <reference lib="dom" />

import type { ComponentType } from "react";
import { createElement } from "react";
import { createRoot, hydrateRoot, type Root } from "react-dom/client";
import type { ReactHydrationOptions } from "../types.ts";

const roots = new WeakMap<HTMLElement, Root>();

/**
 * Hydrate a React component on the client
 * Attaches interactivity to server-rendered HTML using React 18's hydrateRoot
 *
 * @param container - DOM element to hydrate into
 * @param Component - React component to hydrate
 * @param props - Component props
 * @param options - Hydration options including error recovery
 */
export function hydrate(
	container: HTMLElement,
	Component: ComponentType<Record<string, unknown>>,
	props: Record<string, unknown>,
	options?: ReactHydrationOptions,
): void {
	try {
		const element = createElement(Component, props);

		const root = hydrateRoot(container, element, {
			onRecoverableError:
				options?.onRecoverableError ||
				((error: unknown) => {
					console.error("React hydration recoverable error:", error);
				}),
		});
		roots.set(container, root);
	} catch (error) {
		console.error("React hydration failed:", error);
		throw error;
	}
}

/** Mount a React component into an empty container (no SSR HTML to hydrate). */
export function mount(
	container: HTMLElement,
	Component: ComponentType<Record<string, unknown>>,
	props: Record<string, unknown>,
): void {
	try {
		const element = createElement(Component, props);
		const root = createRoot(container);
		root.render(element);
		roots.set(container, root);
	} catch (error) {
		console.error("React mount failed:", error);
		throw error;
	}
}

/** Tear down a hydrated React root before a client-navigation DOM swap. */
export function unmount(container: HTMLElement): void {
	const root = roots.get(container);
	if (!root) return;
	root.unmount();
	roots.delete(container);
}

/**
 * Generate hydration script for React islands
 * This script is injected into the page to enable client-side hydration
 * Supports all hydration conditions: on:client, on:visible, on:idle, on:interaction
 *
 * @returns JavaScript code as a string for client-side hydration
 */
export function getHydrationScript(): string {
	const script = [
		"import { hydrate } from '@useavalon/react/client';",
		"",
		"// Helper to hydrate a single island",
		"async function hydrateIsland(el) {",
		"  const src = el.getAttribute('data-src');",
		"  const propsStr = el.getAttribute('data-props');",
		"  const props = propsStr ? JSON.parse(propsStr) : {};",
		"  ",
		"  try {",
		"    const module = await import(src);",
		"    const Component = module.default || module;",
		"    hydrate(el, Component, props);",
		"  } catch (error) {",
		"    console.error('Failed to hydrate React island:', error);",
		"  }",
		"}",
		"",
		"// Process all React islands based on their hydration condition",
		"document.querySelectorAll('[data-framework=\"react\"]').forEach((el) => {",
		"  const condition = el.getAttribute('data-condition') || 'on:client';",
		"  ",
		"  if (condition === 'on:client') {",
		"    // Hydrate immediately",
		"    hydrateIsland(el);",
		"  } else if (condition === 'on:visible') {",
		"    // Hydrate when element becomes visible",
		"    const observer = new IntersectionObserver((entries) => {",
		"      entries.forEach((entry) => {",
		"        if (entry.isIntersecting) {",
		"          hydrateIsland(entry.target);",
		"          observer.disconnect();",
		"        }",
		"      });",
		"    });",
		"    observer.observe(el);",
		"  } else if (condition === 'on:idle') {",
		"    // Hydrate when browser is idle",
		"    if ('requestIdleCallback' in window) {",
		"      requestIdleCallback(() => hydrateIsland(el));",
		"    } else {",
		"      // Fallback for browsers without requestIdleCallback",
		"      setTimeout(() => hydrateIsland(el), 200);",
		"    }",
		"  } else if (condition === 'on:interaction') {",
		"    // Hydrate on first user interaction",
		"    const events = ['click', 'touchstart', 'mouseenter', 'focus'];",
		"    const hydrateOnce = () => {",
		"      hydrateIsland(el);",
		"      events.forEach(event => el.removeEventListener(event, hydrateOnce));",
		"    };",
		"    events.forEach(event => el.addEventListener(event, hydrateOnce, { once: true, passive: true }));",
		"  }",
		"});",
	].join("\n");

	return script;
}

/**
 * Check if a container is ready for hydration
 *
 * @param container - DOM element to check
 * @returns True if container has content to hydrate
 */
export function isHydrationReady(container: HTMLElement): boolean {
	return container.hasChildNodes();
}

/**
 * Clean up hydration artifacts after hydration is complete
 *
 * @param container - DOM element to clean up
 */
export function cleanupHydration(container: HTMLElement): void {
	// Remove hydration-specific attributes
	delete container.dataset.framework;
	delete container.dataset.src;
	delete container.dataset.props;
	delete container.dataset.condition;
}

// packages/integrations/lit/client/hydration.ts
/**
 * Lit Client-Side Hydration
 *
 * Uses official @lit-labs/ssr-client hydration support.
 */

/// <reference lib="dom" />
/// <reference lib="dom.iterable" />

import type { LitElement } from "lit";
import type { LitHydrationOptions } from "../types.ts";

// Import hydration support - MUST be first
import "./lit-hydrate-support.ts";

/**
 * Hydrate a server-rendered Lit component
 */
export function hydrate(
	container: HTMLElement,
	ElementClass: typeof LitElement,
	props: Record<string, unknown>,
	options?: LitHydrationOptions,
): void {
	if (Object.hasOwn(container.dataset, "litHydrated")) return;

	const tagName =
		container.dataset.tagName ||
		(ElementClass as any).elementName ||
		ElementClass.name.replaceAll(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

	if (!tagName) {
		throw new Error("Could not determine tag name for Lit component");
	}

	if (options?.defer) {
		const trigger = () => performHydration(container, ElementClass, tagName, props);
		if (typeof requestIdleCallback === "undefined") {
			setTimeout(trigger, 0);
		} else {
			requestIdleCallback(trigger);
		}
		return;
	}

	performHydration(container, ElementClass, tagName, props);
	container.dataset.litHydrated = "true";
}

/** Mount a Lit element into an empty container (no SSR custom element to hydrate). */
export function mount(
	container: HTMLElement,
	ElementClass: typeof LitElement,
	props: Record<string, unknown>,
): void {
	const tagName =
		container.dataset.tagName ||
		(ElementClass as any).elementName ||
		ElementClass.name.replaceAll(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

	if (!tagName) {
		throw new Error("Could not determine tag name for Lit component");
	}

	if (!customElements.get(tagName)) {
		customElements.define(tagName, ElementClass as any);
	}

	const newElement = document.createElement(tagName);
	for (const [key, value] of Object.entries(props)) {
		(newElement as any)[key] = value;
	}
	container.appendChild(newElement);
	container.dataset.litHydrated = "true";
}

/** Lit has no framework tree to dispose; clear the hydration marker so a later scan can re-run. */
export function unmount(container: HTMLElement): void {
	delete container.dataset.litHydrated;
}

function performHydration(
	container: HTMLElement,
	ElementClass: typeof LitElement,
	tagName: string,
	props: Record<string, unknown>,
): void {
	const element = container.querySelector(tagName);

	if (!element) {
		mount(container, ElementClass, props);
		return;
	}

	// Register custom element if needed
	if (!customElements.get(tagName)) {
		customElements.define(tagName, ElementClass as any);
	}

	// Remove defer-hydration to trigger Lit's hydration
	if (element.hasAttribute("defer-hydration")) {
		element.removeAttribute("defer-hydration");
	}
}

/**
 * Get hydration script for automatic island hydration
 */
export function getHydrationScript(): string {
	return `
    import { hydrate } from '@useavalon/lit/client';
    
    document.querySelectorAll('[data-framework="lit"]').forEach(async (el) => {
      const src = el.getAttribute('data-src');
      const propsJson = el.getAttribute('data-props');
      const props = propsJson ? JSON.parse(propsJson) : {};
      
      try {
        const module = await import(src);
        const Component = module.default || module;
        hydrate(el, Component, props);
      } catch (error) {
        console.error('Failed to hydrate Lit component:', src, error);
      }
    });
  `;
}
