// packages/integrations/react/client/hydration.ts
// Client-side hydration logic for React components
/// <reference lib="dom" />

import type { ComponentType } from "react";
import { createElement } from "react";
import { createRoot, hydrateRoot, type Root } from "react-dom/client";
import type { ReactHydrationOptions } from "../types.ts";

const roots = new WeakMap<HTMLElement, Root>();

/**
 * Hydrate a React component on the client
 * Attaches interactivity to server-rendered HTML using React 18's hydrateRoot
 *
 * @param container - DOM element to hydrate into
 * @param Component - React component to hydrate
 * @param props - Component props
 * @param options - Hydration options including error recovery
 */
export function hydrate(
	container: HTMLElement,
	Component: ComponentType<Record<string, unknown>>,
	props: Record<string, unknown>,
	options?: ReactHydrationOptions,
): void {
	try {
		const element = createElement(Component, props);

		const root = hydrateRoot(container, element, {
			onRecoverableError:
				options?.onRecoverableError ||
				((error: unknown) => {
					console.error("React hydration recoverable error:", error);
				}),
		});
		roots.set(container, root);
	} catch (error) {
		console.error("React hydration failed:", error);
		throw error;
	}
}

/** Mount a React component into an empty container (no SSR HTML to hydrate). */
export function mount(
	container: HTMLElement,
	Component: ComponentType<Record<string, unknown>>,
	props: Record<string, unknown>,
): void {
	try {
		const element = createElement(Component, props);
		const root = createRoot(container);
		root.render(element);
		roots.set(container, root);
	} catch (error) {
		console.error("React mount failed:", error);
		throw error;
	}
}

/** Tear down a hydrated React root before a client-navigation DOM swap. */
export function unmount(container: HTMLElement): void {
	const root = roots.get(container);
	if (!root) return;
	root.unmount();
	roots.delete(container);
}

/**
 * Check if a container is ready for hydration
 *
 * @param container - DOM element to check
 * @returns True if container has content to hydrate
 */
export function isHydrationReady(container: HTMLElement): boolean {
	return container.hasChildNodes();
}

/**
 * Clean up hydration artifacts after hydration is complete
 *
 * @param container - DOM element to clean up
 */
export function cleanupHydration(container: HTMLElement): void {
	// Remove hydration-specific attributes
	delete container.dataset.framework;
	delete container.dataset.src;
	delete container.dataset.props;
	delete container.dataset.condition;
}

// packages/integrations/solid/client/hydration.ts
/**
 * Solid client-side hydration
 *
 * Solid's hydrate() reads globalThis._$HY for the hydration context
 * (events, completed set, resource cache). The SSR output injects a
 * script that initialises _$HY before any island scripts run.
 *
 * In per-island mode each island is a separate ES module with its own
 * Solid runtime. Before calling hydrate() we ensure _$HY exists and
 * reset _$HY.done so Solid enters hydration mode rather than falling
 * back to client render.
 *
 * @module solid/client/hydration
 */

import { createComponent, hydrate as solidHydrate, render as solidRender } from "solid-js/web";
import type { SolidComponent, SolidHydrationOptions } from "../types.ts";

const disposers = new WeakMap<Element, () => void>();

/**
 * Initialise the Solid hydration context on globalThis if absent,
 * and reset the `done` flag so each island hydrates independently.
 */
function ensureHydrationContext(): void {
	if (!(globalThis as any)._$HY) {
		(globalThis as any)._$HY = {
			events: [],
			completed: new WeakSet(),
			r: {},
			fe() {},
		};
	}
	(globalThis as any)._$HY.done = false;
}

/**
 * Hydrate a Solid component into an existing server-rendered container.
 *
 * @param container - The `<avalon-island>` element with SSR content
 * @param Component - Solid component function
 * @param props     - Component props (serialised from SSR)
 */
export async function hydrate(
	container: Element,
	Component: SolidComponent,
	props: Record<string, unknown> = {},
	_options: SolidHydrationOptions = {},
): Promise<void> {
	if (!container) {
		throw new Error("Container element is required for hydration");
	}
	if (!Component || typeof Component !== "function") {
		throw new Error(`Invalid Solid component: expected function, got ${typeof Component}`);
	}

	const element = container as HTMLElement;
	const renderId = element.dataset.solidRenderId || element.dataset.renderId;

	ensureHydrationContext();
	const dispose = solidHydrate(() => createComponent(Component, props), element, {
		renderId: renderId || "",
	});
	if (typeof dispose === "function") {
		disposers.set(container, dispose);
	}
}

/** Mount a Solid component into an empty container (no SSR HTML to hydrate). */
export function mount(
	container: Element,
	Component: SolidComponent,
	props: Record<string, unknown> = {},
): void {
	if (!container) {
		throw new Error("Container element is required for mount");
	}
	if (!Component || typeof Component !== "function") {
		throw new Error(`Invalid Solid component: expected function, got ${typeof Component}`);
	}

	const dispose = solidRender(() => createComponent(Component, props), container);
	if (typeof dispose === "function") {
		disposers.set(container, dispose);
	}
}

/** Tear down a hydrated Solid tree before a client-navigation DOM swap. */
export function unmount(container: Element): void {
	const dispose = disposers.get(container);
	if (!dispose) return;
	dispose();
	disposers.delete(container);
}
